webtalk_init -webtalk_dir /home/lowie/Documents/IIW/S8/HW_SW_Codesign/exercises/E101/E101.sim/sim_1/behav/xsim/xsim.dir/picorv_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 23 20:34:25 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "28f65c88-a687-488e-a20d-91cc5b74d5d7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fecca39794b9437aaf5a70c2c22e4665" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "openSUSE" -context "user_environment"
webtalk_add_data -client project -key os_release -value "openSUSE Leap 15.3" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1628.912 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "7" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "34.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "127488_KB" -context "xsim\\usage"
webtalk_transmit -clientid 9654140 -regid "" -xml /home/lowie/Documents/IIW/S8/HW_SW_Codesign/exercises/E101/E101.sim/sim_1/behav/xsim/xsim.dir/picorv_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/lowie/Documents/IIW/S8/HW_SW_Codesign/exercises/E101/E101.sim/sim_1/behav/xsim/xsim.dir/picorv_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/lowie/Documents/IIW/S8/HW_SW_Codesign/exercises/E101/E101.sim/sim_1/behav/xsim/xsim.dir/picorv_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
